### Matrix product is calculated manually to verify the evaluation

**Question Solution**

$$ A = \begin{bmatrix}-1\\ 2\\ 3 \end{bmatrix} B = \begin{bmatrix}0 \\ 2 \\ 1 \end{bmatrix}=7 $$


**Step 1 multiplication:**
$$ \begin{bmatrix}(-1*0)+(2*2)+(3*1) \end{bmatrix} $$


**Step 2 addition:**
$$
\begin{bmatrix}0+4+3\end{bmatrix} $$


**Final answer**
$$
\begin{bmatrix}7\end{bmatrix} $$


## Problem One: 

In [2]:
import numpy as np

#creating a numpy array
a = np.array([[-1,2,3]])
b = np.array([[0,2,1]])


In [2]:
np.inner(a,b) #you can also use the inner function to do the evaluation

array([[7]])

In [4]:
#to do this evaluation also again you can use a single [square bracket] in passing the array list
a = np.array([-1,2,3]) 
b = np.array([0,2,1])
np.dot(a,b)

7

### Additional Exercise

In [8]:
a,b

(array([-1,  2,  3]), array([0, 2, 1]))

In [14]:
a = np.arange(0,2,1) #creating a range function

In [15]:
a

array([0, 1])

In [19]:
a = np.linspace(-1,2,3) #inline spacing function

In [20]:
a

array([-1. ,  0.5,  2. ])

In [9]:
b = np.linspace(0,2,1)

In [10]:
b

array([0.])

In [11]:
b = np.arange(0,2,1)

In [12]:
b

array([0, 1])